mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info

dns:
  enable: true
  listen: '0.0.0.0:1053'

  default-nameserver:
  - 'tls://223.5.5.5:853' # aliyun
  - '223.6.6.6' # aliyun
  - 'https://120.53.53.53/dns-query' # tencent
  - '119.29.29.29' # tencent

  nameserver:
  - system
  
  fallback:
  - '8.8.4.4'
  - 'https://1.1.1.1/dns-query'
  - '168.95.192.1'

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 127.0.0.1/8, 0.0.0.0/32] }
  fake-ip-filter:
  - '*.*.xboxlive.com'
  - '*.126.net'
  - '*.example'
  - '*.ff14.sdo.com'
  - '*.ffxiv.com'
  - '*.finalfantasyxiv.com'
  - '*.home.arpa'
  - '*.invalid'
  - '*.kuwo.cn'
  - '*.lan'
  - '*.linksys.com'
  - '*.linksyssmartwifi.com'
  - '*.local'
  - '*.localdomain'
  - '*.localhost'
  - '*.mcdn.bilivideo.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - '*.music.163.com'
  - '*.music.migu.cn'
  - '*.n.n.srv.nintendo.net'
  - '*.ntp.org.cn'
  - '*.router.asus.com'
  - '*.square-enix.com'
  - '*.test'
  - '*.time.edu.cn'
  - '*.xiami.com'
  - '*.y.qq.com'
  - +.battlenet.com.cn
  - +.cmbchina.com
  - +.cmbimg.com
  - +.media.dssott.com
  - +.msftconnecttest.com
  - +.msftncsi.com
  - +.n0808.com
  - +.nflxvideo.net
  - +.pool.ntp.org
  - +.qq.com
  - +.sandai.net
  - +.srv.nintendo.net
  - +.stun.*.*
  - +.stun.*.*.*
  - +.stun.*.*.*.*
  - +.stun.*.*.*.*.*
  - +.stun.playstation.net
  - +.tencent.com
  - +.wargaming.net
  - +.wggames.cn
  - +.wotgame.cn
  - +.wowsgame.cn
  - amobile.music.tc.qq.com
  - api-jooxtt.sanook.com
  - api.joox.com
  - aqqmusic.tc.qq.com
  - dl.stream.qqmusic.qq.com
  - dns.msftncsi.com
  - ff.dorado.sdo.com
  - heartbeat.belkin.com
  - isure.stream.qqmusic.qq.com
  - joox.com
  - lens.l.google.com
  - local.adguard.org
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - mesu.apple.com
  - mobileoc.music.tc.qq.com
  - music.163.com
  - music.migu.cn
  - music.taihe.com
  - musicapi.taihe.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - proxy.golang.org
  - shark007.net
  - songsearch.kugou.com
  - streamoc.music.tc.qq.com
  - stun.l.google.com
  - swcdn.apple.com
  - swdist.apple.com
  - swdownload.apple.com
  - swquery.apple.com
  - swscan.apple.com
  - time-ios.apple.com
  - time.*.apple.com
  - time.*.com
  - time.*.edu.cn
  - time.*.gov
  - time1.*.com
  - time1.cloud.tencent.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - trackercdn.kugou.com
  - www.msftconnecttest.com
  - www.msftncsi.com
  - xbox.*.*.microsoft.com
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - y.qq.com

proxies: []
proxy-groups: []
rules:
    - RULE-SET,ai_non_ip,AI
    - RULE-SET,stream_tw_non_ip,Taiwan

    - RULE-SET,apple_cdn,Apple
    - RULE-SET,apple_services,Apple
    - RULE-SET,apple_cn_non_ip,DIRECT

    - RULE-SET,microsoft_cdn_non_ip,Microsoft
    - RULE-SET,microsoft_non_ip,Microsoft

    - RULE-SET,lan_non_ip,DIRECT
    - RULE-SET,domestic_non_ip,DIRECT
    - RULE-SET,direct_non_ip,DIRECT

    - RULE-SET,global_non_ip,手动选择

    - RULE-SET,domestic_ip,DIRECT

    - IP-CIDR,0.0.0.0/8,DIRECT
    - IP-CIDR,10.0.0.0/8,DIRECT
    - IP-CIDR,100.64.0.0/10,DIRECT
    - IP-CIDR,127.0.0.0/8,DIRECT
    - IP-CIDR,169.254.0.0/16,DIRECT
    - IP-CIDR,172.16.0.0/12,DIRECT
    - IP-CIDR,192.168.0.0/16,DIRECT
    - IP-CIDR,224.0.0.0/4,DIRECT
    - IP-CIDR6,::1/128,DIRECT
    - IP-CIDR6,fc00::/7,DIRECT
    - IP-CIDR6,fe80::/10,DIRECT

    - 'DOMAIN-SUFFIX,cn,DIRECT'
    - 'DOMAIN-KEYWORD,-cn,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,手动选择'
    
rule-providers:
# 台湾相关流媒体
  stream_tw_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/stream_tw.txt
    path: ./sukkaw_ruleset/stream_tw_non_ip.txt

  ai_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./sukkaw_ruleset/ai_non_ip.txt

  apple_cdn:
    type: http
    behavior: domain
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
    path: ./sukkaw_ruleset/apple_cdn.txt

  apple_services:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/apple_services.txt
    path: ./sukkaw_ruleset/apple_services.txt
  
  apple_cn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt
    path: ./sukkaw_ruleset/apple_cn_non_ip.txt

  microsoft_cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
    path: ./sukkaw_ruleset/microsoft_cdn_non_ip.txt

  microsoft_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
    path: ./sukkaw_ruleset/microsoft_non_ip.txt
  

  lan_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./sukkaw_ruleset/lan_non_ip.txt

  domestic_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
    path: ./sukkaw_ruleset/domestic_non_ip.txt
  direct_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
    path: ./sukkaw_ruleset/direct_non_ip.txt
  global_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
    path: ./sukkaw_ruleset/global_non_ip.txt
  domestic_ip:
    type: http
    behavior: classical
    format: text
    interval: 43200
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
    path: ./sukkaw_ruleset/domestic_ip.txt
