mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info

dns:
  enable: true

  default-nameserver:
  - '114.114.114.114'
  - '119.29.29.29'
  - '223.5.5.5'

  nameserver:
  - 'tls://223.5.5.5:853'
  - 'tls://223.6.6.6:853'
  - 'https://doh.pub/dns-query'
  - 'https://dns.alidns.com/dns-query'
  
  fallback:
  - 'https://dns.cloudflare.com/dns-query'
  - 'https://doh.dns.sb/dns-query'

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.*.xboxlive.com'
  - '*.126.net'
  - '*.example'
  - '*.ff14.sdo.com'
  - '*.ffxiv.com'
  - '*.finalfantasyxiv.com'
  - '*.home.arpa'
  - '*.invalid'
  - '*.kuwo.cn'
  - '*.lan'
  - '*.linksys.com'
  - '*.linksyssmartwifi.com'
  - '*.local'
  - '*.localdomain'
  - '*.localhost'
  - '*.mcdn.bilivideo.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - '*.music.163.com'
  - '*.music.migu.cn'
  - '*.n.n.srv.nintendo.net'
  - '*.ntp.org.cn'
  - '*.router.asus.com'
  - '*.square-enix.com'
  - '*.test'
  - '*.time.edu.cn'
  - '*.xiami.com'
  - '*.y.qq.com'
  - +.battlenet.com.cn
  - +.cmbchina.com
  - +.cmbimg.com
  - +.media.dssott.com
  - +.msftconnecttest.com
  - +.msftncsi.com
  - +.n0808.com
  - +.nflxvideo.net
  - +.pool.ntp.org
  - +.qq.com
  - +.sandai.net
  - +.srv.nintendo.net
  - +.stun.*.*
  - +.stun.*.*.*
  - +.stun.*.*.*.*
  - +.stun.*.*.*.*.*
  - +.stun.playstation.net
  - +.tencent.com
  - +.wargaming.net
  - +.wggames.cn
  - +.wotgame.cn
  - +.wowsgame.cn
  - amobile.music.tc.qq.com
  - api-jooxtt.sanook.com
  - api.joox.com
  - aqqmusic.tc.qq.com
  - dl.stream.qqmusic.qq.com
  - dns.msftncsi.com
  - ff.dorado.sdo.com
  - heartbeat.belkin.com
  - isure.stream.qqmusic.qq.com
  - joox.com
  - lens.l.google.com
  - local.adguard.org
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - mesu.apple.com
  - mobileoc.music.tc.qq.com
  - music.163.com
  - music.migu.cn
  - music.taihe.com
  - musicapi.taihe.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - proxy.golang.org
  - shark007.net
  - songsearch.kugou.com
  - streamoc.music.tc.qq.com
  - stun.l.google.com
  - swcdn.apple.com
  - swdist.apple.com
  - swdownload.apple.com
  - swquery.apple.com
  - swscan.apple.com
  - time-ios.apple.com
  - time.*.apple.com
  - time.*.com
  - time.*.edu.cn
  - time.*.gov
  - time1.*.com
  - time1.cloud.tencent.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - trackercdn.kugou.com
  - www.msftconnecttest.com
  - www.msftncsi.com
  - xbox.*.*.microsoft.com
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - y.qq.com

proxies: []
proxy-groups: []

rules: []
